---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: hosts:mons:mgrs:osds:rgws:grafana-server
  gather_facts: true
  become: true
  tasks:
    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  vars_files:
    - vars/main.yml
    - vars/maas.yml

  tags:
    - always


- name: Install checks for host networking
  hosts: hosts:mons:mgrs:osds:rgws:grafana-server
  gather_facts: true
  become: true
  pre_tasks:
    - name: Test that network interfaces exist
      fail:
        msg: "The specified network interfaces {{ item.name }} doesn't exist, consider setting the 'maas_network_checks_list' variable to override these interfaces"
      with_items:
        - "{{ maas_network_checks_list }}"
      when:
        - "hostvars[inventory_hostname]['ansible_' + (item.name | replace('-', '_'))] is not defined"

  tasks:
    - name: Install network throughput checks
      template:
        src: "templates/rax-maas/network_throughput.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/network_throughput-{{ item.0.name }}-{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_together:
        - "{{ maas_network_checks_list }}"

    - name: Install bonding interface status check
      template:
        src: "templates/rax-maas/host_bonding_iface_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/host_bonding_iface_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when: maas_bonding_interfaces is defined and (maas_bonding_interfaces | length) > 0

    - name: Install network statistics check
      template:
        src: "templates/rax-maas/network_stats_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/network_stats_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"

  vars_files:
    - vars/main.yml
    - vars/maas.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-hosts-network

# maas ovs checks jira RPCOS-76
- name: Install checks for ovs
  hosts: neutron_openvswitch_agent
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:
    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Install ovs bridge physical port check
      template:
        src: "templates/rax-maas/ovs_bridge_physical_port_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/ovs-br_physical_port_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Install ovs bridge ext flow check
      template:
        src: "templates/rax-maas/ovs_br_ext_flow_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/ovs_br_ext_flow_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Install ovs bridge br-int canary flow check
      template:
        src: "templates/rax-maas/br_int_canary_flow_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/br_int_canary_flow_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"

  vars_files:
    - vars/main.yml
    - vars/maas.yml

  tags:
    - maas-hosts-ovs
